### ISSUE TITLE
Console Colors

### ISSUE THREAD

**Issue by rafegoldberg** [OverZealous/gulp-task-listing#13]
Fantastic little utility you've got goin’ on here! Only thing I find wanting is customization controls. Would be nice to be able to change the log formatting– i.e. heading text, line separators, console colors, etc. Just a thought!

**Comment by OverZealous** [comment]
Hey there, glad you like the library.

To be honest, I'm not planning on putting any more work into this library, as it's really designed for just this simple use.  It's small enough that I recommend just forking it if you want to extend it with any changes (or even just hard-code it into a task, since it's less than 70 lines of code).

There's also another, more active library called [gulp-help](https://github.com/chmontgomery/gulp-help) which might be more able to suit your needs. It has a lot of improvements over mine that makes it much more flexible.
