### ISSUE TITLE
Why not specific the chalk version?

### ISSUE THREAD

**Issue by towry** [OverZealous/gulp-task-listing#16]
https://github.com/OverZealous/gulp-task-listing/blob/f207b1c1d2a52c87948e88f2b4db9f5c997e4eeb/package.json#L19

You use `chalk: "*"` and it use `chalk 5.x` and `require() of ES modules is not supported.` error happened.

**Comment by OverZealous** [comment]
Looks like there's been a PR open since 2017 to fix this. I'm not really supporting this library any more, but I'll try to get that merged in and redeployed today.

That being said, there's another library, [gulp-help](https://github.com/chmontgomery/gulp-help), which is more actively maintained. I'd recommend switching to that or one of the other forks.

**Comment by OverZealous** [comment]
I went ahead and merged and published that version. I don't even know if it works anymore, since the test suite doesn't run on the version of Node I have installed.
